# Generated by Django 4.2.23 on 2026-04-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('travel_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rsvp_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvped_profiles', to='countries.country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='visited_countries',
            field=models.ManyToManyField(blank=True, related_name='visited_by_profiles', to='countries.country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
    ]
