# Generated by Django 4.2.23 on 2026-04-16 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_pendingcountrysubmission'),
        ('travel_users', '0002_profile_rsvp_country_profile_visited_countries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rsvp_country',
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='UpcomingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_trip_profiles', to='countries.country')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_trip', to='travel_users.profile')),
            ],
        ),
    ]
