# Generated by Django 4.2.23 on 2026-04-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCountrySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('city_or_region', models.CharField(blank=True, max_length=100)),
                ('hotel_recommendation', models.TextField(blank=True)),
                ('safety_tip', models.TextField(blank=True)),
                ('caution_areas', models.TextField(blank=True)),
                ('perfect_weekend', models.TextField(blank=True)),
                ('hidden_gem', models.TextField(blank=True)),
                ('pro_tip', models.TextField(blank=True)),
                ('people_attribute', models.TextField(blank=True)),
                ('favorite_thing', models.TextField(blank=True)),
                ('lived_experience', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
