# Generated by Django 4.2.23 on 2026-05-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_pendingcountrysubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
